### ISSUE TITLE
코드 확인 한 번 부탁드려요

### ISSUE THREAD

**Issue by hslee2008** [NoBrain0917/SearchBook-API#1]
계속 '학교 정보가 없습니다.'라고 뜹니다.

`schName`은 지워도 문제가 되지 않는것 같습니다.
그리고 `shcCode`는 이렇게 바꾸어 보았습니다.

```
schCode = body.substring(
  body.indexOf('javascript:selectSchool(') + 25,
  body.indexOf('javascript:selectSchool(') + 25 + 5
)
```

저는 중2인데 YSC 대회 참가에서 독서교육종합시스템 API가 필요합니다.

한 번 코드 확인 부탁드립니다.

감사합니다.

**Comment by NoBrain0917** [comment]
학교 코드불러오는건 정상인데 학교 도서 검색 부분에서 문제가 발생하는 것 같네요.

이 코드가 2년전에 만들어진거라 그 당시 기준으로 만들었는데 지금은 또 바뀌었나보네요

최대한 빠른 시일 내에 고쳐보도록 하겠습니다.

**Comment by NoBrain0917** [comment]
수정하엿스빈다

**Comment by hslee2008** [comment]
감사합니다 :)
