### ISSUE TITLE
경기도 에러

### ISSUE THREAD

**Issue by hslee2008** [NoBrain0917/SearchBook-API#2]
실례하지만

1. 계속 경기도만 `"unable to verify the first certificate"`이라고 뜹니다.
2. 혹시 Rest API라 사용 가능하게 하실 수 있나요? 지금은 Node 파일로만 있지만 API로 만들면 좋을 것 갍습니다.
3. 직접 빌릴 수 있는 링크를 삽입할 수 있나요?

감사합니다!

**Comment by NoBrain0917** [comment]
1. 문제는 확인했는데 제가 지금 코로나에 걸려서 빠른 시일내에 고치긴 어려울것 같습니다

2, 3. 말을 좀 이해하지 못했는데 자세히 설명 가능할까요

**Comment by NoBrain0917** [comment]
조금 더 확인해보니 수도권 지역만 되네요.. 지역마다 리퀘스트 규칙이 다 다른가봅니다

**Comment by hslee2008** [comment]
2. Firebase처럼 Rest API를 배포할 수 있나요?
3. 제가 잘 모르는 부분이어서 그런데 혹시 학교 도서관으로 직접 들어가서 빌릴 수 있게 만들 수 있나요? 예를 들면, 한 책에 대한 정보를 가지고 오고 링크가 따라와서 누르면 바로 빌릴 수 있게.

**Comment by NoBrain0917** [comment]
현재 고치고 있긴한데 axios 모듈의 문제인지 정확한 이유는 모르겠지만 울산, 세종, 강원만 안되네요.

조금 더 시도하볼거지만 계속해서 안되면 그냥 세 지역만 빼고 커밋하겠습니다...

**Comment by NoBrain0917** [comment]
모든 버그를 고치고 커밋했습니다.

2. RestAPI로 배포하는건 좀 힐들것 같고, YSC대회에서 node.js를 사용하신다면 express, app 관련 다 빼고 searchBookFromSchoolName(localName, bookName, schoolName)을 사용하시면 됩니다.
3. 학교 도서관으로 바로 리다이렉트 해주는 링크는 독서교육종합지원시스템에서 딱히 나와있지 않아 추가하지 않았습니다.

**Comment by hslee2008** [comment]
제 깃허브 fork에서 https://littlechildwriter-school.onrender.com 로 @NoBrain0917 님의 코드를 수정해서 배포했습니다
